name: Rclone
description: Rclone is a command line program to sync files and directories to and from various providers.
version: 0.1.0
slug: rclone-conf
url: https://github.com/ElVit/hassio-addons/rclone-conf
startup: once
boot: manual
hassio_role: default
hassio_api: true
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons:rw
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  config_file: /config/addons-config/rclone/rclone.conf
  jobs:
    - name: Sync job
      source: /share/sourceDir
      destination: DummyRemote:/destinationDir
      command: sync
      options: --dry-run --verbose
schema:
  config_file: str
  jobs:
    - name: str
      source: str
      destination: str
      command: str
      options: str
